var Good = require("good");
var GoodConsole = require("good-console");
var Chairo = require("chairo");
var AuthCookie = require('hapi-auth-cookie');


// Good

exports.good = {

    register: Good,
    options: {
        reporters: [{
            reporter: GoodConsole,
            events: {
                //ops: "*",
                log: "*", // maps to the "log" event 
                response: "*", // maps to either the "response" or "tail" event
                error: "*", // maps to the "request-error" event
                request: "*" // maps to the hapi "request" event (generated by request.log())
            }
        }]
    }

};


// Chairo 

exports.chairo = {
    register: Chairo,
    options: {
        log: "silent"
    }
};


// Hapi Auth Cookie

exports.authCookie = {
    register: AuthCookie,
    options: {}
};


