var Hapi = require("hapi");
var Hoek = require("hoek");
var Config = require("config");
var Utils = require("./common/utils");

var internals = {
	plugins: [],
	api: require("./api"),
	//web: require("./web")
};

// TODO: dummy api and web plugins


// Good
internals.plugins.push({
    register: require("good"),
    options: {
        reporters: [{
            reporter: require("good-console"),
            events: {
                //ops: "*",
                log: "*", // maps to the "log" event 
                response: "*", // maps to either the "response" or "tail" event
                error: "*", // maps to the "request-error" event
                request: "*" // maps to the hapi "request" event (generated by request.log())
            }
        }]
    }
});


internals.init = function(){

	server = new Hapi.Server();
	server.connection({
    	port: Config.get("port")
	});

	server.register(internals.plugins, function(err) {

	    Hoek.assert(!err, 'Failed registration of plugins: ' + err);
	    console.log("1");

		server.register([internals.api], function(err){

	    	Hoek.assert(!err, 'Failed registration of plugins: ' + err);
	    	console.log("2");

	    	server.start(function(err) {

		    	Hoek.assert(!err, 'Failed start server: ' + err);
	    		console.log("3");
		    	console.log('Server started at: ' + server.info.uri);
		    });
		});    
	});

    // make sure we always have a "credentials" object on request.auth
    server.ext("onPostAuth", function(request, reply) {
        request.auth.credentials = request.auth.credentials || {};
        return reply.continue();
    });

	Utils.registerServer(server);

};

internals.init();
